### ISSUE TITLE
What's the best way to share changes?

### ISSUE THREAD

**Issue by dewittn** [curtistimson/hugo-theme-massively#85]
Hello,

Thanks for all the work you did to migrate this theme to Hugo. 

I recently used this theme on a personal project and made several improvements to it that I thought other people would benefit from. Those improvements include.

- Support for Shortcodes including buttons, images, subheaders, boxes, and more.
- Support for Sections, tags, and other taxonomies
- Support for Base Templates and Blocks
- Refactored code and theme logic

My goal was to make this theme look and function a lot more like the original https://html5up.net/ template, while taking advantage of all of the features of Hugo.

My issue now is that I'm unsure how to best share my changes with this project. I've never contributed on GitHub before so I'm pretty sure I went about this the wrong way, because I made all my modifications without generating individual pull requests.

I'm happy to submit a pull request for all my changes but I've generated 20 commits so far and I realize that might be a lot of code to review. Do you have any suggestions on how to proceed? 

If you would like to checkout my code you can find it at: https://github.com/dewittn/hugo-theme-massively/tree/theme-refactor

Thanks again for all the work that went into this project. 

All the best,
Nelson

**Comment by Kaligule** [comment]
Hello Nelson,

(note that I am not the maintainer of the repo, just someone who also likes this theme). It is cool that you want to share your improvements :)
I don't know how familiar you are with git, so feel free to ask if things are not clear. (By the way, the communication in this repository is pretty slow, we will have to have patience)

There are multiple ways to get your commits in order - rebases come to mind. But the way I like most (because it is not destructive in any way) is to work with cherrypicking (I like [this site](http://think-like-a-git.net/sections/rebase-from-the-ground-up/cherry-picking-explained.html) for a general explanation):

I will assume that you have your repo checked out locally. For each feature that you want to create your own pull-request for:

- Check out the last commit that your and the "original" repository have in common. (I think it is `dfd8a3` for you.
- Create a new branch "feature-branch" and check it out.
- cherrypick the commits from master master that you want in your feature branch. This will create a copy of that commit in your current branch, without altering the original commit.
- you have now a branch that contains a subset of your changes on master. Push it to github and create a pull request for it.

Does this help you?

**Comment by curtistimson** [comment]
Apologies for my late reply @dewittn. I agree with @Kaligule's points regarding cherry picking. It'll be much easier to review and test, if the changes are introduced to the main repository in smaller chunks.

Thanks also for showing your interest in improving this theme :)

**Comment by dewittn** [comment]
@Kaligule and @curtistimson Thanks for reply. I'll look into cherrypicking and setup a pull request for a smaller set of changes.

In the meantime I've setup a demo site incase you are interested in seeing the final product.

https://hugo-theme-massively.nelsonroberto.com
